# <center>流畅的Python</center>
## 第二章 序列构成的数组
### 1. 列表推导和生成器表达式
**示例2-1 把一个字符串变成Unicode码位的列表**

In [1]:
symbols = '$€¥¢£₷'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
print(codes)

[36, 8364, 165, 162, 163, 8375]


**示例2-2 把字符串变成Unicode码位的另外一种写法**

In [2]:
symbols = '$€¥¢£₷'
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 8364, 165, 162, 163, 8375]


**示例2-3 用列表推导和map/filter组合来创建同样的表单**

In [4]:
symbols = '$€¥¢£₷'
beyond_ascii1 = [ord(symbol) for symbol in symbols if(ord(symbol) > 127)]
print(beyond_ascii1)

beyond_ascii2 = list(filter(lambda c: c>127, map(ord, symbols)))
print(beyond_ascii2)

[8364, 165, 162, 163, 8375]
[8364, 165, 162, 163, 8375]


**示例2-4 是用列表推导计算笛卡尔积**

In [5]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)

tshirts = [(color, size) for size in sizes for color in colors]
print('\n')
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]


[('black', 'S'), ('white', 'S'), ('black', 'M'), ('white', 'M'), ('black', 'L'), ('white', 'L')]


**示例2-5 用生成器表达式初始化元组和数组**

In [6]:
symbols = '$€¥¢£₷'
print(tuple(ord(symbol) for symbol in symbols))

from array import array
print(array('I', (ord(symbol) for symbol in symbols)))

(36, 8364, 165, 162, 163, 8375)
array('I', [36, 8364, 165, 162, 163, 8375])


**示例2-6 使用生成器表达式计算笛卡尔积**

In [7]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ((color, size) for color in colors for size in sizes):
    print(tshirt)

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


### 2. 元组

**示例2-7 把元组用做记录**

In [8]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passort in sorted(traveler_ids):
    print('%s / %s' % passort)
print('\n')
for country, _ in traveler_ids:
    print(country)


BRA / CE342567
ESP / XDA205856
USA / 31195855


USA
BRA
ESP


**元组拆包示例**

In [11]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude, longitude, '\n')

a, b = 'a', 'b'
a, b = b, a
print(a, b, '\n')

print(divmod(20, 8))
t = (20, 8)
#quotient, reminder = divmod(t)
quotient, reminder = divmod(*t)
print(quotient, reminder, '\n')

33.9425 -118.408056 

b a 

(2, 4)
2 4 



**用*来处理剩下的元素**

In [13]:
a, b, *rest = range(5)
print(a, b, rest)

a, b, *rest = range(3)
print(a, b, rest)

a, b, *rest = range(2)
print(a, b, rest)

a, *body, c, d = range(5)
print(a, body, c, d)

*head, b, c, d = range(5)
print(head, b, c, d)

0 1 [2, 3, 4]
0 1 [2]
0 1 []
0 [1, 2] 3 4
[0, 1] 2 3 4


**示例2-8 用嵌套元组来获取经度**

In [3]:
metro_areas = [('Tokyo', 'JP', 36.933, (35.689722, 139.691667)), 
               ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)), 
               ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)), 
               ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)), 
               ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)), 
              ]

print('{:15} | {:^9} | {:^9}'.format('city', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if(longitude <= 0):
        print(fmt.format(name, latitude, longitude))

city            |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


**示例2-9 定义和使用具名元组** 

In [4]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))
36.933
(35.689722, 139.691667)


**示例2-10 具名元组的属性和方法**

In [7]:
print(City._fields, '\n')

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
print(delhi._asdict(), '\n')
for key, value in delhi._asdict().items():
    print(key + ':', value)

('name', 'country', 'population', 'coordinates') 

OrderedDict([('name', 'Delhi NCR'), ('country', 'IN'), ('population', 21.935), ('coordinates', LatLong(lat=28.613889, long=77.208889))]) 

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


### 3. 切片
**示例2-11 纯文本文件形式的收据以一行字符串的形式被解析**

In [11]:
invoice = """
0.... 6.................................40..........52...55.......
1909  Pimoroni PiBrella                 $17.50      3    $52.50
1489  6mm Tactile Switch x20            $4.95       2     $9.90
1510  Panavise Jr. - PV-201             $28.00      1    $28.00
1601  PiTFT Mini Kit 320x24             $34.95      1    $34.95
"""

SKU = slice(1, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

$17.50       Pimoroni PiBrella                 
$4.95        6mm Tactile Switch x20            
$28.00       Panavise Jr. - PV-201             
$34.95       PiTFT Mini Kit 320x24             
 


**示例2-12 一个包含三个列表的列表，嵌套的三个列表各自有三个元素来代表井字游戏的一行方块**

In [41]:
board = [['_'] * 3 for i in range(3)]
for item in board:
    print(item)
print('\n')
board[1][2] = 'X'
for item in board:
    print(item)
print('\n')
print('', id(board), '\n', id(board[0]), id(board[1]), id(board[2]), '\n')
print('', id(board[0][0]), id(board[0][1]), id(board[0][2]), '\n', 
      id(board[1][0]), id(board[1][1]), id(board[1][2]), '\n', 
      id(board[2][0]), id(board[2][1]), id(board[2][2]))

['_', '_', '_']
['_', '_', '_']
['_', '_', '_']


['_', '_', '_']
['_', '_', 'X']
['_', '_', '_']


 4538999112 
 4537797256 4537822600 4548110344 

 4323953328 4323953328 4323953328 
 4323953328 4323953328 4354204704 
 4323953328 4323953328 4323953328


**示例2-13 包含三个指向同一对象的引用的列表是毫无用处的**

In [42]:
board = [['_'] * 3] * 3
for item in board:
    print(item)
print('\n')
board[1][2] = 'X'
for item in board:
    print(item)
print('\n')
print('', id(board), '\n', id(board[0]), id(board[1]), id(board[2]), '\n')
print('', id(board[0][0]), id(board[0][1]), id(board[0][2]), '\n',
      id(board[1][0]), id(board[1][1]), id(board[1][2]), '\n', 
      id(board[2][0]), id(board[2][1]), id(board[2][2]))

['_', '_', '_']
['_', '_', '_']
['_', '_', '_']


['_', '_', 'X']
['_', '_', 'X']
['_', '_', 'X']


 4537820168 
 4547606280 4547606280 4547606280 

 4323953328 4323953328 4354204704 
 4323953328 4323953328 4354204704 
 4323953328 4323953328 4354204704


**补充示例说明**

In [43]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)
    print(id(row))

print('\n')
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)
    print(id(row))

4547607048
4547607048
4547607048


4537820168
4537837768
4537812040


**序列的增量赋值**

In [44]:
l = [1, 2, 3]
print(l)
print(id(l), '\n')
l *= 2
print(l)
print(id(l), '\n')

t = (1, 2, 3)
print(t)
print(id(t), '\n')
t *= 2
print(t)
print(id(t), '\n')

[1, 2, 3]
4547605448 

[1, 2, 3, 1, 2, 3]
4547605448 

(1, 2, 3)
4539289248 

(1, 2, 3, 1, 2, 3)
4539375880 



**示例2-15 没人料到的结果：t[2]被改动了，但也有异常抛出**

In [45]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [46]:
print(t)

(1, 2, [30, 40, 50, 60])


**示例2-16 s[a]=b 背后的字节码**

In [48]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


### 4. bisect
**在有序序列中用bisect查找某个元素的插入位置**

In [55]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

if(__name__ == '__main__'):
    if(sys.argv[-1] == 'left'):
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

print('DEMO: ', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO:  bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


**示例2-18 根据一个分数，找到它所对应的成绩**

In [57]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

print([grade(score) for score in [33, 99, 77, 70, 89, 90, 100]])

['F', 'A', 'C', 'C', 'B', 'A', 'A']


**示例2-19 insort可以保持有序序列的顺序**

In [58]:
import bisect
import random

SIZE = 7
random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


### 5. 当列表不是首选时
**示例2-20 一个浮点型数组的创建，存入文件和从文件读取的过程**

In [59]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
print(floats[-1])

fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
print(floats2[-1])

0.5963321947530882
0.5963321947530882


**示例2-21 通过改变数组中的一个字节来更新数组里某个元素的值**

In [61]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))
print(memv[0])

memv_oct = memv.cast('B')
print(memv_oct.tolist())
memv_oct[5] = 4
print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


**示例2-22 对numpy.ndarray的行和列进行基本操作**

In [65]:
import numpy as np
a = np.arange(12)
print(a)
print(type(a))
print(a.shape)

a.shape = 3, 4
print('\n', a, '\n')
print(a[2])
print(a[2, 1])
print(a[:, 1])
print('\n', a.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 8  9 10 11]
9
[1 5 9]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**示例2-23 使用双向队列**

In [ ]:
from collections import deque

dp = deque(range(10), maxlen=10)
print("\nOriginal: \n", dq)

dp.rotate(3)
print('\nRotate 3: \n', dq)

dq.rotate(-4)
print("\nRotate -4: \n", dq)

dq.appendleft(-1)
print("\nAppend Left -1: \n", dq)

dq.extend([11, 22, 33])
print('\nExtend: \n', dq)

dq.extendleft